const users = [
  {
    id: 1,
    userName: "Himal Kafle",
    profilePic: "person/1.jpg",
  },
  {
    id: 2,
    userName: "Ayush Poudel",
    profilePic: "person/6.jpg",
  },
  {
    id: 3,
    userName: "Lakshimi Kafle",
    profilePic: "person/4.jpg",
  },
  {
    id: 4,
    userName: "Ayusha Shah",
    profilePic: "person/2.jpg",
  },
  {
    id: 5,
    userName: "Himal Kafle",
    profilePic: "person/1.jpg",
  },
  {
    id: 6,
    userName: "Ayush Poudel",
    profilePic: "person/6.jpg",
  },
  {
    id: 7,
    userName: "Lakshimi Kafle",
    profilePic: "person/4.jpg",
  },
  {
    id: 8,
    userName: "Ayusha Shah",
    profilePic: "person/2.jpg",
  },
  {
    id: 9,
    userName: "Lakshimi Kafle",
    profilePic: "person/4.jpg",
  },
  {
    id: 10,
    userName: "Himal Kafle",
    profilePic: "person/1.jpg",
  },
];

const friends = [
  {
    id: 1,
    userName: "Himal Kafle",
    profilePic: "person/1.jpg",
  },
  {
    id: 2,
    userName: "Ayush Poudel",
    profilePic: "person/6.jpg",
  },
  {
    id: 3,
    userName: "Lakshimi Kafle",
    profilePic: "person/4.jpg",
  },
  {
    id: 4,
    userName: "Ayusha Shah",
    profilePic: "person/2.jpg",
  },
  {
    id: 5,
    userName: "Himal Kafle",
    profilePic: "person/3.jpg",
  },
  {
    id: 6,
    userName: "Himal Kafle",
    profilePic: "person/5.jpg",
  },
  {
    id: 7,
    userName: "Himal Kafle",
    profilePic: "person/7.jpg",
  },
  {
    id: 8,
    userName: "Himal Kafle",
    profilePic: "person/8.jpg",
  },
  {
    id: 9,
    userName: "Himal Kafle",
    profilePic: "person/1.jpg",
  },
  {
    id: 10,
    userName: "Ayush Poudel",
    profilePic: "person/6.jpg",
  },
  {
    id: 11,
    userName: "Lakshimi Kafle",
    profilePic: "person/4.jpg",
  },
  {
    id: 12,
    userName: "Ayusha Shah",
    profilePic: "person/2.jpg",
  },
  {
    id: 13,
    userName: "Himal Kafle",
    profilePic: "person/3.jpg",
  },
  {
    id: 14,
    userName: "Himal Kafle",
    profilePic: "person/5.jpg",
  },
  {
    id: 15,
    userName: "Himal Kafle",
    profilePic: "person/7.jpg",
  },
  {
    id: 16,
    userName: "Himal Kafle",
    profilePic: "person/8.jpg",
  },
];

const Posts = [
  {
    id: 1,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "5 mins ago",
    postCaption: "Hey its my first post:)",
    postImg: "person/1.jpg",
    postLikes: 53,
    postComments: 23,
  },
  {
    id: 2,
    postProfile: "person/2.jpg",
    postUsername: "Ayusha Shah",
    postTime: "5 hrs ago",
    postCaption: "aint i beautiful in photos",
    postImg: "person/2.jpg",
    postLikes: 63,
    postComments: 38,
  },
  {
    id: 3,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "7 days ago",
    postCaption: "it was an awesome day",
    postImg: "person/3.jpg",
    postLikes: 35,
    postComments: 69,
  },
  {
    id: 4,
    postProfile: "person/4.jpg",
    postUsername: "Laxmi Kafle",
    postTime: "2 months ago",
    postCaption: "i am shy to look into the camera",
    postImg: "person/4.jpg",
    postLikes: 82,
    postComments: 28,
  },
  {
    id: 5,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "1 day ago",
    postCaption: "may peace flourish always",
    postImg: "person/5.jpg",
    postLikes: 27,
    postComments: 61,
  },
  {
    id: 6,
    postProfile: "person/6.jpg",
    postUsername: "Ayush Poudel",
    postTime: "2 months ago",
    postCaption: "finally, i changed my profile",
    postImg: "person/6.jpg",
    postLikes: 60,
    postComments: 53,
  },
  {
    id: 7,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "2 hrs ago",
    postCaption: "isnt it a beautiful scene",
    postImg: "person/7.jpg",
    postLikes: 68,
    postComments: 85,
  },
  {
    id: 8,
    postProfile: "person/6.jpg",
    postUsername: "Ayush Poudel",
    postTime: "5 months ago",
    postCaption: "with boys at my brother's marriage anniversery",
    postImg: "person/8.jpg",
    postLikes: 18,
    postComments: 61,
  },
];

const profilePosts = [
  {
    id: 1,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "5 mins ago",
    postCaption: "Hey its my first post:)",
    postImg: "person/1.jpg",
    postLikes: 53,
    postComments: 23,
  },
  {
    id: 2,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "5 mins ago",
    postCaption: "Hey its my first post:)",
    postImg: "person/2.jpg",
    postLikes: 53,
    postComments: 23,
  },
  {
    id: 3,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "5 mins ago",
    postCaption: "Hey its my first post:)",
    postImg: "person/3.jpg",
    postLikes: 53,
    postComments: 23,
  },
  {
    id: 4,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "5 mins ago",
    postCaption: "Hey its my first post:)",
    postImg: "person/4.jpg",
    postLikes: 53,
    postComments: 23,
  },
  {
    id: 5,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "5 mins ago",
    postCaption: "Hey its my first post:)",
    postImg: "person/5.jpg",
    postLikes: 53,
    postComments: 23,
  },
  {
    id: 6,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "5 mins ago",
    postCaption: "Hey its my first post:)",
    postImg: "person/6.jpg",
    postLikes: 53,
    postComments: 23,
  },
  {
    id: 7,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "5 mins ago",
    postCaption: "Hey its my first post:)",
    postImg: "person/7.jpg",
    postLikes: 53,
    postComments: 23,
  },
  {
    id: 8,
    postProfile: "person/1.jpg",
    postUsername: "Himal Kafle",
    postTime: "5 mins ago",
    postCaption: "Hey its my first post:)",
    postImg: "person/8.jpg",
    postLikes: 53,
    postComments: 23,
  },
];

export { Posts, users, profilePosts, friends };
